#!/bin/bash

RED='\e[41m'
BLUE='\e[44m'
ORANGE='\e[46m'
NC='\e[0m'
trap 'rm $HOME/{.installed_kernels,.available_kernels}' EXIT

in_array() {
    local haystack=${1}[@]
    local needle=${2}
    for i in ${!haystack}; do
        if [[ ${i} == ${needle} ]]; then
            return 0
        fi
    done
    return 1
}

function get_current_inst_kernel {
	currentlyinstkernel=$(grep -v -f .installed_kernels)
	echo "$currentlyinstkernel"
}

function get_current_running_kernel {
	currentlyrunningkernel=$(grep -v -f .running_kernel)
	echo "$currentlyrunningkernel"
}

function install_kernel {
current_kernel=$(get_current_inst_kernel)
echo -e "Currently installed kernel(s): $current_kernel"
PS3="which kernel do you wish to install? (press ctrl+c to cancel): "
# Gather the results in an array.
kernels=($(grep -v -f .installed_kernels .available_kernels) "cancel")
select pick in "${kernels[@]}"
do
	case $pick in
		cancel)
			break
			;;		
		*)	if in_array picks $pick; then
					picks=($(printf -- '%s\n' "${picks[@]}" | grep -v $pick));	
				else
					picks+=("$pick")
			fi
	        printf 'Selected: %s\n' "${picks[*]}"
			;;		
	esac
done
if [[ $picks ]]; then
    if [ "$picks" == "$current_kernel" ]; then
    	STATUSVAR=1
    else
    	printf 'Installing %s\n' "${picks[*]}"
    	sudo mhwd-kernel -i "${picks[@]}"
    	STATUSVAR=$?
    fi
fi
}

function remove_kernel {
current_kernel=$(get_current_running_kernel)
echo -e "Currently running kernel: $current_kernel"
PS3="which kernel do you wish to remove? (press ctrl+c to cancel): "
# Gather the results in an array.
kernels=($(grep -v -f .running_kernel .installed_kernels) "cancel")
select pick in "${kernels[@]}"
do
	case $pick in
		cancel)
			exit
			;;		
		*)	if in_array picks $pick; then
					picks=($(printf -- '%s\n' "${picks[@]}" | grep -v $pick));	
				else
					picks+=("$pick")
			fi
	        printf 'Selected: %s\n' "${picks[*]}"
			;;		
	esac
done

if [[ $picks ]]; then
    printf 'Removing %s\n' "${picks[*]}"
    sudo mhwd-kernel -r "${picks[@]}"
    STATUSVAR=$?
fi
}

mhwd-kernel -li | awk 'NR==1 {print $4}' | tr -d '()' > .running_kernel
mhwd-kernel -li | awk 'NR > 2 { print $2}' > .installed_kernels
mhwd-kernel -l | awk 'NR > 1 { print $2}' > .available_kernels

    while true; do
    clear
    echo ""
    echo -e "                             $NC ::mhwd-tui::  "
    echo -e " ┌────────────────────────────────────────────────────────────────────────────┐"
    echo -e " │    1   Install Kernel                        2   Remove kernel             │"
    echo -e " │    3   Use free graphics                     4   Use nonfree graphics      │"
    echo -e " │    5   List installed drivers                                              │"    
    echo -e " └────────────────────────────────────────────────────────────────────────────┘"
    echo -e "          Select a number                       0 Exit mhwd-tui"
    echo ""
    read -s -n1 choix
    case $choix in
        1)
            echo
            install_kernel
            echo ""
            ;;
        2)
            echo
            remove_kernel
            echo ""
            ;;
        3)
            echo
            sudo mhwd -a pci free 0300
            echo ""
            echo "Done. Press any key to continue"
            read
            echo ""

            ;;
        4)
            echo
            sudo mhwd -a pci nonfree 0300
            echo ""
            echo "Done. Press any key to continue"
            read
            echo ""
            ;;
        5)
            echo
            mhwd -li -d
            echo ""
            echo "Press any key to continue"
            read
            echo ""
            ;;

        0)
            clear && exit
            read
            ;;
        *)
            echo -e "$RED Wrong option $NC"
            echo "Wait and try again later..."
            echo ""
            sleep 3
            clear
            ;;
    esac
    done
fi
